export const LOAD_DATA = 'LOAD_DATA'
export const LOAD_PHONEBOOKS_SUCCESS = 'LOAD_PHONEBOOKS_SUCCESS'
export const LOAD_PHONEBOOKS_FAILURE = 'LOAD_PHONEBOOKS_FAILURE'

export const ADD_DATA = 'ADD_DATA'
export const ADD_PHONEBOOKS_SUCCESS = 'ADD_PHONEBOOKS_SUCCESS'
export const ADD_PHONEBOOKS_FAILURE = 'ADD_PHONEBOOKS_FAILURE'

export const EDIT_DATA = 'EDIT_DATA'
export const EDIT_PHONEBOOKS_SUCCESS = 'EDIT_PHONEBOOKS_SUCCESS'
export const EDIT_PHONEBOOKS_FAILURE = 'EDIT_PHONEBOOKS_FAILURE'

export const DELETE_DATA = 'DELETE_DATA'
export const DELETE_PHONEBOOKS_SUCCESS = 'DELETE_PHONEBOOKS_SUCCESS'
export const DELETE_PHONEBOOKS_FAILURE = 'DELETE_PHONEBOOKS_FAILURE'